/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: JanesBT (https://sketchfab.com/JanesBt)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/planet-earth-babd284930204736a938915ceb0a6535
title: Planet Earth
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";
import { Stars } from "@react-three/drei";



export default function EarthImpo(props) {
  const { nodes, materials } = useGLTF('/earthImpo.gltf')
  const earthImpoRef = useRef()

  useFrame(({ clock }) => {
    const elapsedTime = clock.getElapsedTime();

    earthImpoRef.current.rotation.y = elapsedTime / 6;
})

  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 1, 0, 0]}>
      <Stars 
        radius={300}
        depth={60}
        count={5000}
        factor={7}
        saturation={0}
        fade={true}
        />
      <meshStandardMaterial  metalness={0.4} roughness={0.7} />
      <sphereGeometry args={[1, 32, 32]} />


        <mesh ref={earthImpoRef} geometry={nodes.Object_2.geometry} material={materials['Material.001']} scale={8} position={[0, 0, 2.78]}/>
      </group>
    </group>
  )
}

useGLTF.preload('/earthImpo.gltf')
