/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: kongle (https://sketchfab.com/minecraftnorge)
license: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
source: https://sketchfab.com/3d-models/mars-7b14d8d8a5b94626a4b2a8a4455297d6
title: Mars
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";
import { Stars } from "@react-three/drei";
import { Cloud } from '@react-three/drei';





export default function Mars(props) {
  const marsRef = useRef()
  useFrame(({ clock }) => {
    const elapsedTime = clock.getElapsedTime();
    marsRef.current.rotation.y = elapsedTime / 6;
  
  })

  const { nodes, materials } = useGLTF('/mars.gltf')

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
      <Stars 
        radius={300}
        depth={60}
        count={5000}
        factor={7}
        saturation={0}
        fade={true}
        />
        <Cloud
  opacity={0.5}
  speed={0.4} // Rotation speed
  width={1} // Width of the full cloud
  depth={3} // Z-dir depth
  segments={20} // Number of particles
/>

        <mesh ref={marsRef} geometry={nodes.Object_2.geometry} material={materials.moon}  scale={1}/>
      </group>
    </group>
  )
}

useGLTF.preload('/mars.gltf')
